import type { Metadata } from "next";
import "./globals.css";
import AdsenseScript from "@/components/ui/ad-Script";
import { AppProvider } from "@/context/AppContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <head>
        <AdsenseScript adId={process.env.NEXT_PUBLIC_ADSENSE_CLIENT_ID!} />
      </head>
      <body className="min-h-full flex flex-col">
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
